# 公有化配置
server:
  port: 8080

spring:
  application:
    name: synuwxy-springboot-note
#  profiles:
#    active: jmail # 指定当前使用哪个配置文件
  mail:
    host: smtp.qq.com
    username: 1062186165@qq.com
    password: patjkqqksxnsbcje
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true