
server:
  port: 8080

spring:
  application:
    name: synuwxy-springboot-note
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mybatis_generator_demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456 #填写自己数据库的密码
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456

# jaeger 配置
opentracing:
  jaeger:
    udp-sender:
      port: 6831
      host: #这里填写jaeger服务端的ip
    log-spans: false
    aop:
      status: true

# mybatis 配置
mybatis:
  type-aliases-package: com.synuwxy.springbootnote.mybatis.entity
  mapper-locations: classpath:mybatis/mapper/*/*.xml