# jaeger 配置
opentracing:
  jaeger:
    udp-sender:
      port: 6831
      host: localhost #这里填写jaeger服务端的ip
    log-spans: false
    rabbitmq:
      enable: true
#    aop:
#      status: false
    http:
      enable: true